export const FOOD_ITEMS = [
  { key: 'airpods' as const,           label: 'AIRPODS',            icon: '/assets/food-airpods.png' },
  { key: 'airwrap' as const,           label: 'AIRWRAP',            icon: '/assets/food-airwrap.png' },
  { key: 'apple' as const,             label: 'APPLE',              icon: '/assets/food-apple.png' },
  { key: 'banana_milk' as const,       label: 'BANANA MILK',        icon: '/assets/food-banana-milk.png' },
  { key: 'basque_cheesecake' as const, label: 'BASQUE CHEESECAKE',  icon: '/assets/food-basque-cheesecake.png' },
  { key: 'black_card' as const,        label: 'BLACK CARD',         icon: '/assets/food-black-card.png' },
  { key: 'boba' as const,              label: 'BOBA',               icon: '/assets/food-boba.png' },
  { key: 'chanel_bag' as const,        label: 'CHANEL BAG',         icon: '/assets/food-chanel-bag.png' },
  { key: 'coffee' as const,            label: 'COFFEE',             icon: '/assets/food-coffee.png' },
  { key: 'dumplings' as const,         label: 'DUMPLINGS',          icon: '/assets/food-dumplings.png' },
  { key: 'gameboy' as const,           label: 'GAMEBOY',            icon: '/assets/food-gameboy.png' },
  { key: 'hong_pao' as const,          label: 'HONG PAO',           icon: '/assets/food-hong-pao.png' },
  { key: 'ice_matcha_latte' as const,  label: 'ICE MATCHA LATTE',   icon: '/assets/food-ice-matcha-latte.png' },
  { key: 'lafufu' as const,            label: 'LAFUFU',             icon: '/assets/food-lafufu.png' },
  { key: 'matcha_soft_serve' as const, label: 'MATCHA SOFT SERVE',  icon: '/assets/food-matcha-soft-serve.png' },
  { key: 'onigiri' as const,           label: 'ONIGIRI',            icon: '/assets/food-onigiri.png' },
  { key: 'ramen' as const,             label: 'RAMEN',              icon: '/assets/food-ramen.png' },
  { key: 'tamagotchi' as const,        label: 'TAMAGOTCHI',         icon: '/assets/food-tamagotchi.png' },
  { key: 'taro_croissant' as const,    label: 'TARO CROISSANT',     icon: '/assets/food-taro-croissant.png' },
  { key: 'tesla' as const,             label: 'TESLA',              icon: '/assets/food-tesla.png' },
  { key: 'van_cleef' as const,         label: 'VAN CLEEF',          icon: '/assets/food-van-cleef.png' },
];
